package:
  name: brem
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch: python
  
test:

  source_files:
    - ./tests
  
  commands:
    - python -c "import os, glob; print ('TESTING IN THIS DIRECTORY' , os.getcwd()); print ([el for el in glob.glob('*')])"
    - python -m unittest discover tests

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - paramiko
    - eqt

about:
  home: https://github.com/paskino/brem
  license: Apache 2.0
  summary: Basic Remote Execution Manager (brem) is a simple Python package that enables the execution on remote machines connected via SSH.
