name: publish_conda

on:
  release:
    types: [published]
  push:
    branches: [ conda-fix ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: paskino/conda-package-publish-action@fix-test_package
      with:
        subDir: 'conda'
        channels: 'conda-forge -c paskino'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        test_all: False
        publish: True
        #publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
